# Generated by Django 4.2.1 on 2023-05-26 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
